# coding: utf-8

# flake8: noqa

"""
    项目名

    项目描述  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: 649641514@qq.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.archives_api import ArchivesApi
from swagger_client.api.medical_records_api import MedicalRecordsApi
from swagger_client.api.test_record_api import TestRecordApi
from swagger_client.api.user_api import UserApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.api_response import ApiResponse
from swagger_client.models.archives import Archives
from swagger_client.models.bone_age import BoneAge
from swagger_client.models.medical_records import MedicalRecords
from swagger_client.models.test_record import TestRecord
from swagger_client.models.user import User
