# coding: utf-8

"""
    项目名

    项目描述  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: 649641514@qq.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bone_age import BoneAge  # noqa: E501
from swagger_client.rest import ApiException


class TestBoneAge(unittest.TestCase):
    """BoneAge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBoneAge(self):
        """Test BoneAge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bone_age.BoneAge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
