# coding: utf-8

"""
    项目名

    项目描述  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: 649641514@qq.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_change_active_put(self):
        """Test case for user_change_active_put

        修改账号状态  # noqa: E501
        """
        pass

    def test_user_change_pwd_put(self):
        """Test case for user_change_pwd_put

        修改账号密码  # noqa: E501
        """
        pass

    def test_user_get(self):
        """Test case for user_get

        用户列表接口  # noqa: E501
        """
        pass

    def test_user_id_delete(self):
        """Test case for user_id_delete

        删除用户  # noqa: E501
        """
        pass

    def test_user_id_get(self):
        """Test case for user_id_get

        查询用户  # noqa: E501
        """
        pass

    def test_user_id_put(self):
        """Test case for user_id_put

        修改用户  # noqa: E501
        """
        pass

    def test_user_login_post(self):
        """Test case for user_login_post

        用户登录  # noqa: E501
        """
        pass

    def test_user_post(self):
        """Test case for user_post

        新建用户  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
