# coding: utf-8

"""
    项目名

    项目描述  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: 649641514@qq.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.archives_api import ArchivesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArchivesApi(unittest.TestCase):
    """ArchivesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.archives_api.ArchivesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archives_get(self):
        """Test case for archives_get

        档案列表  # noqa: E501
        """
        pass

    def test_archives_id_delete(self):
        """Test case for archives_id_delete

        删除档案  # noqa: E501
        """
        pass

    def test_archives_id_get(self):
        """Test case for archives_id_get

        查询用户档案  # noqa: E501
        """
        pass

    def test_archives_id_put(self):
        """Test case for archives_id_put

        修改档案信息  # noqa: E501
        """
        pass

    def test_archives_post(self):
        """Test case for archives_post

        新建档案  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
